### ISSUE TITLE
Trace Servlet is throwing NPE

### ISSUE THREAD

**Issue by kgrgreer** [foam-framework/foam2#804]
java.lang.NullPointerException
	at java.util.Vector.<init>(Vector.java:171)
	at foam.nanos.http.ServletHandler$RequestWrapper.getHeaders(ServletHandler.java:50)
	at foam.nanos.http.ServletHandler$RequestWrapper.getCookies(ServletHandler.java:54)
	at foam.nanos.http.TraceWebAgent.execute(TraceWebAgent.java:24)
	at foam.nanos.http.WebAgentServlet.service(WebAgentServlet.java:39)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at foam.nanos.http.NanoRouter.service(NanoRouter.java:50)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at foam.nanos.http.ServletHandler.handle(ServletHandler.java:311)
	at foam.nanos.http.NanoHttpHandler.handle(NanoHttpHandler.java:34)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:748)

@waseem-chamaa

**Comment by waseem-chamaa** [comment]
https://github.com/foam-framework/foam2/pull/806

**Comment by kgrgreer** [comment]
Fixed.
